Removed rounding on hyprland configurations.

diff --git a/swaypkgs b/swaypkgs
--- a/swaypkgs
+++ b/swaypkgs
@@ -3,17 +3,6 @@
 set -e
 
 # AUR Setup
-if command -v paru >/dev/null 2>&1; then
-    echo "󰋑 paru is already installed."
-else
-    echo "󰏗 Installing paru.."
-    git clone https://aur.archlinux.org/paru-bin.git >/dev/null 2>&1
-    cd paru-bin >/dev/null 2>&1
-    makepkg -si --noconfirm >/dev/null 2>&1
-    cd .. >/dev/null 2>&1
-    rm -rf paru-bin >/dev/null 2>&1
-    echo " paru installation complete."
-fi
 if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
     echo "󰖷 Setting up Chaotic AUR..."
     {
@@ -29,6 +18,14 @@ echo " Chaotic AUR added successfully."
 else
     echo "󰋑 Chaotic AUR is already configured."
 fi
+if ! command -v paru &> /dev/null; then
+    echo "󰏗 Installing paru..."
+    sudo pacman -S --noconfirm paru &> /dev/null
+    echo -e " Successfully installed $package.\n"
+else
+    echo "󰋑 paru is already installed."
+fi
+
 
 # List of packages to install
 packages=(
@@ -81,16 +78,8 @@ for package in "${packages[@]}"; do
         echo -e "󰏗 Installing $package..."
         if paru -S --noconfirm --quiet "$package" &>/dev/null; then
             echo -e " Successfully installed $package.\n"
-
-    # Enable services if needed
-    case "$package" in
-        auto-cpufreq)
-            echo "󰈆 Enabling and starting hyprpolkitagent..."
-            systemctl --user enable --now hyprpolkitagent.service &>/dev/null
-            ;;
-    esac
-else
-    echo " Failed to install $package." >&2
+        else
+            echo " Failed to install $package." >&2
         fi
     fi
 done
