Full NixOS configuration files.

diff --git a/scripts/.bin/power-saver b/scripts/.bin/power-saver
--- a/scripts/.bin/power-saver
+++ b/scripts/.bin/power-saver
@@ -1,32 +1,37 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
 BATTERY_DEVICE=$(upower -e | grep BAT)
 KBD_DEVICE="asus::kbd_backlight"
 current_state=""
 
 # Ensure Hyprland is running
-if ! pgrep -x Hyprland > /dev/null; then
+if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
     echo "Hyprland is not running. Exiting."
     exit 1
 fi
 
+# Get the connected monitor name
+MONITOR=$(hyprctl monitors | awk '/Monitor/ {print $2}' | head -n 1)
+
+# Ensure upower is working
+if [ -z "$BATTERY_DEVICE" ]; then
+    echo "Battery device not found. Is upower enabled?"
+    exit 1
+fi
+
 # Start monitoring battery state
-upower --monitor | grep --line-buffered "changed.*$BATTERY_DEVICE" | while read -r line; do
+upower --monitor | grep --line-buffered "$BATTERY_DEVICE" | while read -r _; do
     new_state=$(upower -i "$BATTERY_DEVICE" | grep -m1 "state:" | awk '{print $2}')
     if [ "$new_state" != "$current_state" ]; then
         current_state="$new_state"
-        current_brightness=$(brightnessctl get)
         if [ "$new_state" = "discharging" ]; then
-            if [ "$current_brightness" != "40" ]; then
-                brightnessctl set 40%
-                brightnessctl --device="$KBD_DEVICE" set 0
-            fi
-            hyprctl keyword monitor "eDP-1,1920x1080@60,auto,1.0"
+            brightnessctl set 40%
+            brightnessctl --device="$KBD_DEVICE" set 0
+            hyprctl keyword monitor "$MONITOR,1920x1080@60,auto,1.0"
         else
-            if [ "$current_brightness" != "80" ]; then
-                brightnessctl set 80%
-                brightnessctl --device="$KBD_DEVICE" set 80%
-            fi
-            hyprctl keyword monitor "eDP-1,1920x1080@120,auto,1.0"
+            brightnessctl set 80%
+            brightnessctl --device="$KBD_DEVICE" set 80%
+            hyprctl keyword monitor "$MONITOR,1920x1080@120,auto,1.0"
         fi
     fi
 done &
